--SCHEDULER 

BEGIN
--CREO UN JOB CHE VERRA' ESEGUITO OGNI AD OGNI PRIMO GIORNO DEL MESE
--TALE JOB EFFETTUERA' UN'OPERAZIONE DI PULIZIA DEL DATABASE ELIMINANDO LE PROMO ORMAI SCADUTE 
DBMS_SCHEDULER.create_job(

	--DEFINISCO NOME DEL JOB
	job_name => 'promo_scad_delete',
	--DEFINISCO TIPO DEL JOB
	job_type => 'PLSQL_BLOCK',
	--WHERE CI DA LA POSSIBILITA' DI ELIMINARE SOLO LE PROMO SCADURE
	job_action => 'BEGIN
					DELETE FROM PROMO
					WHERE DATA_FINE_PROMO<SYSDATE;
					END;',
	--DATA INIZIO JOB
	start_date => TO_TIMESTAMP('01-09-2020 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),
	--FREQUENZA TEMPORALE DI ATTIVAZIONE
	repeat_interval => 'FREQ=MONTHLY; BYMONTHDAY=1; BYHOUR=0; BYMINUTE=0; BYSECOND=0',
	enabled => TRUE,
	comments => 'Cancellazione promo scadute');
	END;
