--VISUALIZZA NOME,COGNOME,TIPO_CARTA E DATA_ACQUISTO DI CHI HA EFFETTUATO UN ACQUISTO
--NEGL'ULTIMI 3 MESI

SELECT CLIENTE.NOME , CLIENTE.COGNOME , CARTA.TIPO_CARTA , ACQUISTO.DATA_ACQUISTO
FROM ((CARTA 
INNER JOIN CLIENTE 
ON CARTA.USERNAME = CLIENTE.USERNAME)
INNER JOIN ACQUISTO
ON CARTA.CODICE_ACQUISTO = ACQUISTO.CODICE_ACQUISTO)
WHERE (SYSDATE - ACQUISTO.DATA_ACQUISTO) < 90
ORDER BY ACQUISTO.DATA_ACQUISTO;

-------------------------------------------------------------------------------------

--VISUALIZZA NOME,COGNOME,USERNAME DI CHI HA EFFETTUATO UN ACQUISTO(CODICE_ACQUISTO),
--VISUALIZZANDO ANCHE LA CARTA UTILIZZATA, DI UNA SCARPA(NOME_SCARPA) 
--CON PREZZO SUPERIORE A 400
--(VISUALIZZANDO DI CONSEGUENZA ANCHE PREZZO,NOME_SCARPE E CODICE_ACQUISTO)

SELECT DISTINCT CLI.NOME, CLI.COGNOME, CLI.USERNAME, SC.NOME_SCARPE, CAR.TIPO_CARTA, SC.PREZZO_SCARPE, ACQ.CODICE_ACQUISTO
FROM (((PRODOTTO PROD JOIN SCARPE SC ON PROD.ID_PRODOTTO = SC.ID_PRODOTTO)
JOIN ACQUISTO ACQ 
ON PROD.CODICE_ACQUISTO = ACQ.CODICE_ACQUISTO) 
JOIN CARTA CAR 
ON CAR.CODICE_ACQUISTO = ACQ.CODICE_ACQUISTO)
JOIN CLIENTE CLI 
ON CLI.USERNAME = CAR.USERNAME
WHERE SC.PREZZO_SCARPE > 399
ORDER BY SC.PREZZO_SCARPE

-------------------------------------------------------------------------------------

--VISUALIZZA NUMERO_MAGAZZINO, LA CAPIENZA E IL TOTALE DEI PRODOTTI CONTENUTI
--ALL'INTERNO DI QUEI MAGAZZINO 

SELECT MA.NUMERO_MAGAZZINO,MAX(MA.CAPIENZA),SUM(CONT.QUANTITA_DISTRIB)
FROM E_CONTENUTA_IN CONT JOIN MAGAZZINO MA ON CONT.NUMERO_MAGAZZINO = MA.NUMERO_MAGAZZINO
GROUP BY MA.NUMERO_MAGAZZINO
ORDER BY MA.NUMERO_MAGAZZINO

-------------------------------------------------------------------------------------

--VISUALIZZA USERNAME, NOME, COGNOME, DATA_INIZIO E DATA_FINE DI TUTTI COLORO
--CHE HANNO ACQUISTATO UN ABBONAMENTO PLATINIUM L'ULTIMO ANNO

SELECT EFF.NOME_ABBONAMENTO,EFF.DATA_INIZIO_ABB, EFF.DATA_FINE_ABB, CLI.USERNAME, CLI.NOME, CLI.COGNOME
FROM EFFETTUA EFF JOIN CLIENTE CLI ON EFF.USERNAME = CLI.USERNAME
WHERE NOME_ABBONAMENTO = 'PLATINUM' AND 
(SYSDATE - EFF.DATA_INIZIO_ABB) < 365
ORDER BY DATA_INIZIO_ABB

