-- CREATE USER ADMIN
CREATE USER ADMIN IDENTIFIED BY psw_admin;
GRANT ALL PRIVILEGES TO ADMIN;


-- CREATE USER CLIENTE
CREATE USER CLIENTE IDENTIFIED BY psw_cliente;
GRANT CREATE SESSION TO CLIENTE;

CREATE ROLE CLIENTI;

GRANT SELECT ON CLIENTE TO CLIENTI;
GRANT SELECT ON CARTA TO CLIENTI;
GRANT SELECT ON ABBONAMENTO TO CLIENTI;
GRANT SELECT ON RELEASE_DAY TO CLIENTI;
GRANT SELECT ON CATALOGO TO CLIENTI;
GRANT SELECT ON ACQUISTO TO CLIENTI;
GRANT SELECT ON PRODOTTO TO CLIENTI;

GRANT CLIENTI TO CLIENTE;


-- CREATE USER GESTORE_VENDITE
CREATE USER GESTORE_VENDITE IDENTIFIED BY psw_vendite;
GRANT CREATE SESSION TO GESTORE_VENDITE;

CREATE ROLE VENDITE;

GRANT SELECT, INSERT, UPDATE, DELETE ON CARTA TO VENDITE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ACQUISTO TO VENDITE;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROMO TO VENDITE;
GRANT SELECT ON CLIENTE TO VENDITE;

GRANT VENDITE TO GESTORE_VENDITE;


-- CREATE USER MANAGER_SERVIZI
CREATE USER MANAGER_SERVIZI IDENTIFIED BY psw_servizi;
GRANT CREATE SESSION TO MANAGER_SERVIZI;

CREATE ROLE SERVIZI;

GRANT SELECT, INSERT, UPDATE, DELETE ON RELEASE_DAY TO SERVIZI;
GRANT SELECT, INSERT, UPDATE, DELETE ON DA_ACCESSO TO SERVIZI;
GRANT SELECT, INSERT, UPDATE, DELETE ON EFFETTUA TO SERVIZI;
GRANT SELECT, INSERT, UPDATE, DELETE ON CATALOGO TO SERVIZI;

GRANT SELECT ON ABBONAMENTO TO SERVIZI;
GRANT SELECT ON CLIENTE TO SERVIZI;
GRANT SELECT ON PRODOTTO TO SERVIZI;

GRANT SERVIZI TO MANAGER_SERVIZI;


-- CREATE USER MANAGER_LOGISTICA
CREATE USER MANAGER_LOGISTICA IDENTIFIED BY psw_logistica;
GRANT CREATE SESSION TO MANAGER_LOGISTICA;

CREATE ROLE LOGISTICA;

GRANT SELECT, INSERT, UPDATE, DELETE ON FORNITORE TO LOGISTICA;
GRANT SELECT, INSERT, UPDATE, DELETE ON FORNITURA TO LOGISTICA;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAGAZZINO TO LOGISTICA;
GRANT SELECT, INSERT, UPDATE, DELETE ON E_CONTENUTA_IN TO LOGISTICA;

GRANT LOGISTICA TO MANAGER_LOGISTICA;


-- CREATE USER GESTORE_PRODOTTI
CREATE USER GESTORE_PRODOTTI IDENTIFIED BY psw_prodotti;
GRANT CREATE SESSION TO GESTORE_PRODOTTI;

CREATE ROLE PRODOTTI;

GRANT SELECT, INSERT, UPDATE, DELETE ON PRODOTTO TO PRODOTTI;
GRANT SELECT, INSERT, UPDATE, DELETE ON CAPI_HYPE TO PRODOTTI;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCARPE TO PRODOTTI;
GRANT SELECT, INSERT, UPDATE, DELETE ON SUDDIVISE_IN TO PRODOTTI;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAGLIA_SCARPE TO PRODOTTI;

GRANT SELECT ON CATALOGO TO PRODOTTI;

GRANT PRODOTTI TO GESTORE_PRODOTTI;


