--VISTA CHE VISUALIZZA USERNAME,NOME,COGNOME ED ETA' DEI CLIENTI
--CON L'ETA' PIU' ALTA 

CREATE VIEW ETA_MAX_MIN AS
SELECT USERNAME, NOME, COGNOME, ETA 
FROM CLIENTE 
WHERE ETA = (SELECT MAX(ETA) FROM CLIENTE) 

-------------------------------------------------------------------------------------------------------------------------------------

----VISTA CHE VISUALIZZA USERNAME,NOME,COGNOME ED ETA' DEI CLIENTI
--CON L'ETA' PIU' BASSA

CREATE VIEW ETA_MAX_MIN AS
SELECT USERNAME, NOME, COGNOME, ETA 
FROM CLIENTE 
WHERE ETA = (SELECT MIN(ETA) FROM CLIENTE) 

-------------------------------------------------------------------------------------------------------------------------------------

--VISTA CHE VISUALIZZA CODICE PROMO, DATA INIZIO E DATA FINE DELLE PROMO
--CHE INIZIANO DAL 1° MAGGIO 2022 IN POI

CREATE VIEW PROSSIME_PROMO AS
SELECT CODICE_PROMO, DATA_INIZIO_PROMO, DATA_FINE_PROMO
FROM PROMO
WHERE DATA_INIZIO_PROMO >= DATE'2022-05-01'

-------------------------------------------------------------------------------------------------------------------------------------

--VISTA CHE VISUALIZZA USERNAME, CODICE ACQUISTO E DATA ACQUISTO
--DI TUTTI GLI ACQUISTI EFFETTUATI NEL 2022

CREATE VIEW UTENTI_ACQUISTI AS
SELECT CARTA.CODICE_ACQUISTO, CARTA.USERNAME, ACQUISTO.DATA_ACQUISTO 
FROM CARTA JOIN ACQUISTO ON CARTA.CODICE_ACQUISTO = ACQUISTO.CODICE_ACQUISTO
WHERE ACQUISTO.DATA_ACQUISTO >= DATE'2022-01-01'

-------------------------------------------------------------------------------------------------------------------------------------

--VISTA CHE VISUALIZZA NOME SCARPE, MODELLO E PREZZO DI TUTTE LE SNEACKERS PRESENTI
--NEL DATABASE

CREATE VIEW SNEACKERS AS
SELECT NOME_SCARPE, MODELLO, PREZZO_SCARPE 
FROM SCARPE
WHERE MODELLO = 'SNEACKERS'

-------------------------------------------------------------------------------------------------------------------------------------

--VISTA CHE VISUALIZZA NOME, TAGLIA E PREZZO DEI CAPI CON
--PREZZO SUPERIORE AI 500€

CREATE VIEW CAPO_PREZZO AS
SELECT NOME_CAPO, TAGLIA, PREZZO_CAPO
FROM CAPI_HYPE
WHERE PREZZO_CAPO >= 150

-------------------------------------------------------------------------------------------------------------------------------------

--VISTA CHE VISUALIZZA NOME,COGNOME, ID FORNITURA E DATA FORNITURA
--DELLE FORNITURE SPEDITE DURANTE GLI ULTIMI 3 MESI

CREATE VIEW ULTIME_FORN AS
SELECT FORNITORE.NOME_FORNITORE, FORNITORE.COGNOME_FORNITORE, 
FORNITURA.ID_FORNITURA, FORNITURA.DATA_FORNITURA 
FROM FORNITURA JOIN FORNITORE ON FORNITURA.AZIENDA_FORNITORE = FORNITORE.AZIENDA_FORNITORE
WHERE (SYSDATE - FORNITURA.DATA_FORNITURA) < 90

-------------------------------------------------------------------------------------------------------------------------------------

--VISTA CHE VISUALIZZA ID FORNITURA, ID PRODOTTO, TAGLIA FORNITA E PREZZO DELLA FORNITURA
--PIU' COSTOSA

CREATE VIEW FORNITURA_MAX AS 
SELECT ID_FORNITURA, ID_PRODOTTO, TAGLIA_FORNITA , PREZZO_FORNITURA
FROM FORNITURA
WHERE PREZZO_FORNITURA = (SELECT MAX(PREZZO_FORNITURA) FROM FORNITURA)

-------------------------------------------------------------------------------------------------------------------------------------

--VISTA CHE VISUALIZZA ID FORNITURA, ID PRODOTTO, TAGLIA FORNITA E PREZZO DELLA FORNITURA
--MENO COSTOSA

CREATE VIEW FORNITURA_MIN AS 
SELECT ID_FORNITURA, ID_PRODOTTO, TAGLIA_FORNITA , PREZZO_FORNITURA
FROM FORNITURA
WHERE PREZZO_FORNITURA = (SELECT MIN(PREZZO_FORNITURA) FROM FORNITURA)

-------------------------------------------------------------------------------------------------------------------------------------

--VISTA CHE VISUALIZZA TUTTI I NOMI DEI CATALOGHI CON FASCIA D'ETA' ADULTO

CREATE VIEW CATALOGHI AS
SELECT NOME_CATALOGO, FASCIA_D_ETA
FROM CATALOGO 
WHERE FASCIA_D_ETA = 'ADULTO'

-------------------------------------------------------------------------------------------------------------------------------------

--VISTA CHE VISUALIZZA NOME,DATA E TIPO DI RELEASE CHE SI TERRANNO SUCCESSIVAMENTE 
--ALLA DATA DI SISTEMA 

CREATE VIEW LAST_RELEASE AS
SELECT NOME_RELEASE, DATA_RELEASE, TIPO_RELEASE
FROM RELEASE_DAY
WHERE DATA_RELEASE > SYSDATE









